### ISSUE TITLE
Compilation error on intel or m1 Mac

### ISSUE THREAD

**Issue by EmeraldLoc** [AloXado320/sm64ex-alo#20]
On an m1 Mac, I get "ld symbol(s) not found for architecture arm64" error when compiling native. Rosetta 2 gets error: "ld: symbol(s) not found for architecture x86_64" I've narrowed it down to sound.s if that helps.
<img width="1627" alt="Screen Shot 2022-03-30 at 3 23 40 PM" src="https://user-images.githubusercontent.com/86802223/160924455-35e3d439-2d99-487f-858f-1fa3f707e6da.png">
<img width="1627" alt="Screen Shot 2022-03-30 at 3 23 44 PM" src="https://user-images.githubusercontent.com/86802223/160924481-1f5a6e79-5e3f-4251-9d41-14d6feeb57d6.png">

**Comment by EmeraldLoc** [comment]
Added more linker flags, so fixed most of linking errors. What is the linker flag for these objects
<img width="292" alt="Screen Shot 2022-04-11 at 7 33 22 PM" src="https://user-images.githubusercontent.com/86802223/162854978-a652b08b-589d-4ea9-879c-ac108952f3eb.png">
?

**Comment by PaulGrandperrin** [comment]
I'm stuck at the same point. Using an x86_64 macOS.
Those symbols are in `sound_data.o`.
The issue is the `sound_data.o` has been assembled using the `mingw` `as` which produce a `mingw` specific object.
The linker then complains about not understanding this object's format and ignores its symbols.

My understanding is that the source of`sound_data.o` can only be assembled using GNU `as`. The `as` from macOS will fail.
However, I don't understand who using `mingw`'s `as` has ever been working before.. because of the different output format.

Pinging people who I think worked on this: @AloXado320 @AuroraWright @Hyenadae @GammaTendonNine

**Comment by EmeraldLoc** [comment]
So I was able to get it to compile, which is nice. It seems to actually come from load.c when you set the data var in audio_init. However, it crashes on launch, more progress :)

**Comment by EmeraldLoc** [comment]
I don't think adding a linker flag will fix it, and honestly I just wanna know why they made the change, I was able to compile the version right before sound_data.s became a thing. Odd.

**Comment by EmeraldLoc** [comment]
ITS WORKING!!! I got it compiled lets go! However there is no audio which is a little akward lol. So in load.c lines 106-109 remove the extern part, then it will compile and launch. However remember to build with RENDER_API=GL_LEGACY or else your screen will be black.

**Comment by EmeraldLoc** [comment]
Making a pr for all fixes done

**Comment by PaulGrandperrin** [comment]
I think this issue should be kept open because the PR doesn't really fix the issue of the sound code not linking properly.
The PR replaces the missing sound data with empty arrays so that the linking doesn't complain.. But the real issue is still there and still need fixing.
